name = "pixel"               
main = "src/index.ts"       
compatibility_date = "2025-07-08"
workers_dev = true

[[kv_namespaces]]
binding = "PIXEL_LOG"
id      = ""   

TG_BOT_TOKEN = ""
TG_CHAT_ID   = ""
